version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      POSTGRES_USER: xmlgenie
      POSTGRES_PASSWORD: xmlgenie_pass
      POSTGRES_DB: xmlgenie_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: